### ISSUE TITLE
Verify iPhone sensor data sanity

### ISSUE THREAD

**Issue by janm399** [eigengo/lift#75]
Check that the acceleration and rotation rates report sane values. The acceleration units are cm/s^2 ("milli Gs"), and we trim at 40m/s^2; when the phone is left without movement, the values should be around 0.

The rotation rate is in mrad/s; given our ranges, we expect fastest rotation to be 4 rotations / second; the maximum value should be 1000π.

**Comment by mpetruska** [comment]
4 rotations / sec is around 25.13 rad/sec, which is 2500 crad / sec.

**Comment by mpetruska** [comment]
Tested the reported values, updated some code, seems okay for now.
Pull request: https://github.com/eigengo/lift/pull/82
