### ISSUE TITLE
Need to be able to run multiple localised versions of LiftLocalApp in AWS

### ISSUE THREAD

**Issue by carlpulley** [eigengo/lift#80]
As a partial step towards deploying Lift into a production environment, we need to be able to run multiple versions of `LiftLocalApp` in their own docker containers and as a viable Akka cluster. The general idea idea is that:
* each container will run a single JVM
* each JVM will host a single actor system
* within each actor system we will run the full set of microservices (i.e. exercise, notification and profile)
* each container will need to expose a REST port and an Akka port
* collection of containers should form an Akka Cluster.

**Comment by anirvanc** [comment]
Don't we also want to also make sure that:
* the different containers would form an Akka Cluster
